export { getCurrentNodeEntry } from './getCurrentNodeEntry';
export { isBlockActive } from './isBlockActive';
export { isMarkActive } from './isMarkActive';
export { toggleBlock } from './toggleBlock';
export { toggleMark } from './toggleMark';
export { isAlignActive } from './isAlignActive';
export { toggleAlign } from './toggleAlign';
export { getEditorRange } from './getEditorRange';
export { setFontSize } from './setFontSize';
export { isTextNode } from './isTextNode';
export { isSelectionValid } from './isSelectionValid';
export { getFontSize } from './getFontSize';
export { saveSelection } from './saveSelection';
export { isNodeEmpty, isElementEmpty } from './isNodeEmpty';
export { insertEmpty } from './insertEmpty';
export { isEmpty, isEmptyElements } from './isEmpty';
export { isValidDesendants } from './isValidDesendants';
