import { app, BrowserWindow, screen } from 'electron';
import { handleWindow } from './channels';
// This allows TypeScript to pick up the magic constant that's auto-generated by Forge's Webpack
// plugin that tells the Electron app where to look for the Webpack-bundled app code (depending on
// whether you're running in development or production).
declare const APP_WEBPACK_ENTRY: string;
declare const APP_PRELOAD_WEBPACK_ENTRY: string;

// Handle creating/removing shortcuts on Windows when installing/uninstalling.
if (require('electron-squirrel-startup')) {
  app.quit();
}

const createWindow = (): void => {
  const mainWindow = new BrowserWindow({
    webPreferences: {
      contextIsolation: true,
      preload: APP_PRELOAD_WEBPACK_ENTRY,
    },
    width: 400,
    height: 400,
    frame: false,
    backgroundColor: '#23315e',
    roundedCorners: true,
    icon: 'favicon.ico',
  });
  // and load the index.html of the app.
  // Open the DevTools.
  //mainWindow.webContents.openDevTools();
  mainWindow.once('ready-to-show', () => {
    const { width, height } = screen.getPrimaryDisplay().workAreaSize;
    mainWindow.setMinimumSize(width, height);
    mainWindow.maximize();
  });
  mainWindow.loadURL(APP_WEBPACK_ENTRY);
  handleWindow(mainWindow);
};

app.whenReady().then(() => {
  createWindow();

  app.on('activate', () => {
    if (BrowserWindow.getAllWindows().length === 0) {
      createWindow();
    }
  });
});

app.on('window-all-closed', () => {
  if (process.platform !== 'darwin') {
    app.quit();
  }
});
